"""empty message

Revision ID: 564d808570c2
Revises: a7492c71b914
Create Date: 2018-06-11 16:37:52.225749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564d808570c2'
down_revision = 'a7492c71b914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_active'), 'task', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_active'), table_name='task')
    # ### end Alembic commands ###
