"""empty message

Revision ID: a7492c71b914
Revises: 
Create Date: 2018-06-11 13:01:45.321229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7492c71b914'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_username', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_admin_username'), 'admin', ['admin_username'], unique=True)
    op.create_table('plugin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_filename', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_plugin_filename'), 'plugin', ['plugin_filename'], unique=True)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('ip_list', sa.PickleType(), nullable=False),
    sa.Column('port_list', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('plugin_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    op.drop_table('task')
    op.drop_index(op.f('ix_plugin_plugin_filename'), table_name='plugin')
    op.drop_table('plugin')
    op.drop_index(op.f('ix_admin_admin_username'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
